export const TYPES = {
  CLEAR_CART: "CLEAR_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  DISPLAY_ITEMS: "DISPLAY_ITEMS",
  LOADING: "LOADING",
};
